clean:
	php artisan cache:clear
	php artisan config:clear
	php artisan route:clear
	php artisan view:clear
	php artisan optimize:clear
	php artisan clear-compiled

install:
	composer install

deploy: clean
	composer dump-autoload
	php artisan config:cache
	php artisan route:cache
	npm run build
	sudo chown -R $(USER):resoftware .
	sudo find ./ -type f -not -path "./vendor/*" -not -path "./node_modules/*" -exec chmod 664 {} \;
	sudo find ./ -type d -not -path "./vendor/*" -not -path "./node_modules/*" -exec chmod 775 {} \;

down:
	php artisan down --refresh=15

test:
	./vendor/pestphp/pest/bin/pest

